### ISSUE TITLE
Connecting directly via bluetooth on Docker image

### ISSUE THREAD

**Issue by da-wolff** [tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#14]
I have tried all sort of things and broken things a few times over here.
I am running this add-on with the latest WebthingsIO gateway docker image.
Any help/ideas would be appreciated.

**After installation I get the following errors:**

2021-02-08 14:47:17.603 INFO   : xiaomi-temperature-humidity-sensor-adapter: 60000
2021-02-08 14:47:17.604 INFO   : xiaomi-temperature-humidity-sensor-adapter: noble warning: adapter state unauthorized, please run as root or with sudo
2021-02-08 14:47:17.605 INFO   : xiaomi-temperature-humidity-sensor-adapter:                or see README for information on running without root/sudo:
2021-02-08 14:47:17.606 INFO   : xiaomi-temperature-humidity-sensor-adapter:                https://github.com/sandeepmistry/noble#running-on-linux
2021-02-08 14:47:17.607 INFO   : xiaomi-temperature-humidity-sensor-adapter: Noble adapter is unauthorized

**Then I attempted the recommended command & received subsequent errors:** 
_sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)_

**NOTE:  This also broke many other add-on modules on my gateway and I had to restore it.**

2021-02-08 14:29:46.375 ERROR  : xiaomi-temperature-humidity-sensor-adapter: Error: Cannot find module 'gateway-addon'
2021-02-08 14:29:46.378 ERROR  : xiaomi-temperature-humidity-sensor-adapter: Require stack:
2021-02-08 14:29:46.381 ERROR  : xiaomi-temperature-humidity-sensor-adapter: - /home/node/.webthings/addons/xiaomi-temperature-humidity-sensor-adapter/lib/xiaomi-temperature-humidity-sensor-adapter.js
2021-02-08 14:29:46.383 ERROR  : xiaomi-temperature-humidity-sensor-adapter: - /home/node/.webthings/addons/xiaomi-temperature-humidity-sensor-adapter/lib/index.js
2021-02-08 14:29:46.384 ERROR  : xiaomi-temperature-humidity-sensor-adapter: - /home/node/webthings/gateway/src/dynamic-require.js
2021-02-08 14:29:46.385 ERROR  : xiaomi-temperature-humidity-sensor-adapter: - /home/node/webthings/gateway/src/platform.js
2021-02-08 14:29:46.389 ERROR  : xiaomi-temperature-humidity-sensor-adapter: - /home/node/webthings/gateway/src/utils.js
2021-02-08 14:29:46.390 ERROR  : xiaomi-temperature-humidity-sensor-adapter: - /home/node/webthings/gateway/src/addon-utils.js
2021-02-08 14:29:46.394 ERROR  : xiaomi-temperature-humidity-sensor-adapter: - /home/node/webthings/gateway/src/addon-loader.js
2021-02-08 14:29:46.395 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-02-08 14:29:46.399 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-02-08 14:29:46.407 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-02-08 14:29:46.408 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at require (internal/modules/cjs/helpers.js:74:18)
2021-02-08 14:29:46.409 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Object.<anonymous> (/home/node/.webthings/addons/xiaomi-temperature-humidity-sensor-adapter/lib/xiaomi-temperature-humidity-sensor-adapter.js:20:25)
2021-02-08 14:29:46.410 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-02-08 14:29:46.411 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-02-08 14:29:46.436 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-02-08 14:29:46.440 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-02-08 14:29:46.441 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     at Module.require (internal/modules/cjs/loader.js:887:19) {
2021-02-08 14:29:46.442 ERROR  : xiaomi-temperature-humidity-sensor-adapter:   code: 'MODULE_NOT_FOUND',
2021-02-08 14:29:46.443 ERROR  : xiaomi-temperature-humidity-sensor-adapter:   requireStack: [
2021-02-08 14:29:46.456 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     '/home/node/.webthings/addons/xiaomi-temperature-humidity-sensor-adapter/lib/xiaomi-temperature-humidity-sensor-adapter.js',
2021-02-08 14:29:46.457 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     '/home/node/.webthings/addons/xiaomi-temperature-humidity-sensor-adapter/lib/index.js',
2021-02-08 14:29:46.461 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     '/home/node/webthings/gateway/src/dynamic-require.js',
2021-02-08 14:29:46.461 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     '/home/node/webthings/gateway/src/platform.js',
2021-02-08 14:29:46.462 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     '/home/node/webthings/gateway/src/utils.js',
2021-02-08 14:29:46.463 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     '/home/node/webthings/gateway/src/addon-utils.js',
2021-02-08 14:29:46.464 ERROR  : xiaomi-temperature-humidity-sensor-adapter:     '/home/node/webthings/gateway/src/addon-loader.js'
2021-02-08 14:29:46.465 ERROR  : xiaomi-temperature-humidity-sensor-adapter:   ]
2021-02-08 14:29:46.466 ERROR  : xiaomi-temperature-humidity-sensor-adapter: }
2021-02-08 14:29:46.625 ERROR  : weather-adapter: Error: Cannot find module 'gateway-addon'

**Comment by da-wolff** [comment]
OK, I have finally got this going after a very long road of discovery.

It was a bit of a 'dodgy' work around in my mind so if anyone has some suggestions or feedback by all means, please let me know.

It seems that after executing this command:  `sudo setcap cap_net_raw+eip $(eval readlink -f which node)`  
all the add-ons seem to lose their expectation of the path to the node_modules.  I do not understand why but I tried running the add-on from the command line to see if it was permissions and it wasn't.  It still kept complaining " Error: Cannot find module 'gateway-addon'  ".

So doing some reading on how Node finds modules if they are not in the expected path(s) or known locations, I understood that it would look 'up' the path-tree until it potentially found them.  
My WebthingsIO installation seems to have all the extra installed 'add-ons' located at:  `/home/node/.webthings/addons`
The main Gateway-Addon was located with the node_modules here:  `/home/node/webthings/gateway`
*Notice one has a `.webthings` in the path & the other is just `webthings`.

It seemed that none of the add-ons could find the other modules once the `setcap` was applied.

Therefore I copied the entire `node_modules` directory from `/home/node/webthings/gateway/node_modules` to here `/home/node/node_modules`.

Then everything just worked !!

So, my question is how can I permanently move the "Node_Modules" to this new location & ensure that WebThings will add anything necessary to the same location when required?

Thank you anyone who may be able to shed some light here.
